server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    com.kakao: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 604800